name: Snake Game

on:
  schedule:
    # Atualizado a cada 5 horas.
    - cron: "0 */5 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v4

      # Repositório que será utilizado para gerar os arquivos.
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ReuelBandeira #Seu usuário
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - run: git status

      # Para as atualizações.
      - name: Commit and Push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add dist/
          git commit -m "Atualização automática do Snake Game" || echo "Nada a commitar"
          git push origin HEAD:master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Publicar no GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
