name: Snake Game

on:
  schedule:
    - cron: "0 */5 * * *"  # Atualiza a cada 5 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Clonar o repositório
      - uses: actions/checkout@v3

      # Rodar a Action para gerar a animação
      - uses: Platane/snk@v2.0.0
        id: snake-gif
        with:
          github_user_name: ReuelBandeira  # Substitua pelo seu nome de usuário

      # Commit e push das mudanças
      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Atualização automática do Snake Game" || echo "Nenhuma mudança para commitar"
          git push origin master

      # Publicar a animação na branch 'output'
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
