name: Snake Game

on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure the dist directory exists
        run: |
          mkdir -p dist
          echo "Diretório dist criado ou já existe."

      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ReuelBandeira
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: List contents of the dist directory
        run: |
          echo "Conteúdo do diretório dist:"
          ls -la dist/
          find dist/ -type f -print

      - name: Check if generated files exist
        run: |
          if [ -f dist/github-contribution-grid-snake.gif ] && [ -f dist/github-contribution-grid-snake.svg ]; then
            echo "Arquivos gerados encontrados."
          else
            echo "Arquivos gerados não encontrados."
            exit 1
          fi

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Add and force commit changes
        run: |
          git add dist/
          git commit -m "Atualizando arquivos de contribuição" || echo "Nada a commitar"
          git push origin HEAD:master --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
