name: Snake Game

on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure the dist directory exists
        run: |
          mkdir -p dist
          echo "Diretório dist criado ou já existe."

      - name: Generate snake game images
        uses: Platane/snk@v3
        id: generate-images
        with:
          github_user_name: ReuelBandeira
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: List contents of the dist directory
        run: |
          echo "Conteúdo do diretório dist:"
          ls -la dist/
          find dist/ -type f -print

      - name: Check if generated files exist
        run: |
          if [ -f dist/github-contribution-grid-snake.gif ] && [ -f dist/github-contribution-grid-snake.svg ]; then
            echo "Arquivos gerados encontrados."
          else
            echo "Arquivos gerados não encontrados."
            exit 1
          fi

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Add and force commit changes
        run: |
          git add dist/
          git commit -m "Atualizando arquivos de contribuição" || echo "Nada a commitar"
          git push origin HEAD:master --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
